version: '3.7'

services:
  traefik:
    image: traefik:v2.4
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/traefik/conf
      - ./certs:/etc/traefik/certs
    command:
      - --api.insecure
      - --log.level=DEBUG
      - --providers.docker.watch=false
      - --providers.file.directory=/etc/traefik/conf

      - --entrypoints.websecure.address=:443
      - --entrypoints.inception.address=:9000
      # As this endpoint must be only accessible locally (don't expose this port)
      - --entrypoints.inception.forwardedheaders.insecure

  whoami:
    image: traefik/whoami:v1.6.0
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: inception
      traefik.http.routers.whoami.rule: Host(`whoami`) && Headers(`X-Forwarded-Tls-Client-Cert-Info`, `NA%3D%221694421756%22%2CNA%3D%221918996295%22`)

  whoami2:
    image: traefik/whoami:v1.6.0
    labels:
      traefik.enable: true
      traefik.http.routers.whoami1.entrypoints: inception
      traefik.http.routers.whoami1.rule: Host(`whoami`) && Headers(`X-Forwarded-Tls-Client-Cert-Info`, `NA%3D%221694355700%22%2CNA%3D%221918996295%22`)
      traefik.http.routers.whoami1.priority: 500
