[tls.options.default]
    minVersion = "VersionTLS12"
    sniStrict = true

[[tls.certificates]]
    certFile = "/etc/traefik/certs/whoami.pem"
    keyFile = "/etc/traefik/certs/whoami-key.pem"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/traefik.localhost.pem"
    keyFile = "/etc/traefik/certs/traefik.localhost-key.pem"
