[tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256",
        "TLS_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
    ]
    curvePreferences = [
        "CurveP521",
        "CurveP384",
    ]
    sniStrict = true

[[tls.certificates]]
    certFile = "/etc/traefik/certs/whoami.pem"
    keyFile = "/etc/traefik/certs/whoami-key.pem"

[[tls.certificates]]
    certFile = "/etc/traefik/certs/traefik.localhost.pem"
    keyFile = "/etc/traefik/certs/traefik.localhost-key.pem"
