version: '3.7'

services:
  traefik:
    image: traefik:v2.4
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/traefik/conf
    command:
      - --api.insecure
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --providers.file.directory=/etc/traefik/conf
  #      - --providers.docker

  whoami:
    image: traefik/whoami:v1.6.0
    labels:
      traefik.enable: false
#      traefik.http.routers.whoami.entrypoints: web
#      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)

  whoamim:
    image: traefik/whoami:v1.6.0
    labels:
      traefik.enable: false
#      traefik.http.routers.whoamim.entrypoints: toto
#      traefik.http.routers.whoamim.rule: Host(`whoami2.localhost`)
