apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pebble-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  # Replace the storageClassName with the storage you use in your Kubernetes cluster.
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
