---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pebble
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pebble
  template:
    metadata:
      labels:
        app: pebble
    spec:
      containers:
        - name: pebble
          image: letsencrypt/pebble:v2.3.0
          command:
            - pebble -config /pebble/config.json
          ports:
            - containerPort: 14000
          env:
            - name: PEBBLE_VA_NOSLEEP
              value: "1"
            - name: PEBBLE_WFE_NONCEREJECT
              value: "0"

          volumeMounts:
            # Here we mount the configuration of the agent.
            - name: pebble-volume
              mountPath: /pebble/

      volumes:
        - name: pebble-volume
          persistentVolumeClaim:
            claimName: pebble-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pebble

spec:
  ports:
    - port: 14000
  selector:
    app: pebble
